!setname 0x0644 DARK JOJO
!setname 0x0645 DARK STAND
!setname 0x0184 JOJO
!setname 0x0185 STAND
!setname 0x0604 JOJO
!setname 0x1f99 DARK STAND
!setname 0x0f98 JOJO
!setname 0x0f99 STAND
!setname 0x1f98 DARK JOJO
